---
- hosts: all
  gather_facts: false
  tasks:
  - name: Create a symbolic link
    file:
        src: /
        dest: /
        state: link
  - name: Update system    
    apt:
      update_cache: yes
      upgrade: yes
