---
- hosts: all
  gather_facts: false
  tasks:
  - name: Install Programms 
    ansible.windows.win_package:
      path: C:\Temp\7z.exe
      product_id: 7-zip
      arguments: /S
      state: present
